In [58]:
import numpy as np

In [59]:
arr_1d = np.array([12,3,4,5,3,2])
print("1D array", arr_1d)

1D array [12  3  4  5  3  2]


In [60]:
arr_2d = np.array([[1,2,3,4],[2,3,4,5]])
print("2d array:\n" ,arr_2d)

2d array:
 [[1 2 3 4]
 [2 3 4 5]]


In [61]:
print(arr_2d)

[[1 2 3 4]
 [2 3 4 5]]


In [62]:
print("dimensions: ",arr_1d.ndim)
print("dimensions: ",arr_2d.ndim)

dimensions:  1
dimensions:  2


In [63]:
for i in arr_2d.flat:
    print(i)


1
2
3
4
2
3
4
5


In [64]:
print(arr_2d[1,2])

4
