In [16]:
import numpy as np

In [17]:
arr_1d = np.array([12,3,4,5,3,2])
print("1D array", arr_1d)

1D array [12  3  4  5  3  2]


In [18]:
arr_2d = np.array([[1,2,3,4],[2,3,4,5]])
print("2d array:\n" ,arr_2d)

2d array:
 [[1 2 3 4]
 [2 3 4 5]]


In [19]:
print(arr_2d)

[[1 2 3 4]
 [2 3 4 5]]


In [20]:
print("dimensions: ",arr_1d.ndim)
print("dimensions: ",arr_2d.ndim)

dimensions:  1
dimensions:  2


In [21]:
for i in arr_2d.flat:
    print(i)


1
2
3
4
2
3
4
5


In [22]:
print(arr_2d[1,2])

4


In [23]:
list_data = [1,2,3,4]
print("multi of list " , list_data*2)

multi of list  [1, 2, 3, 4, 1, 2, 3, 4]


# array vs list in numpy
- operation perform on array's each element but ooperation perform on list(suppose as one element)

In [25]:
print("multi of array ", arr_1d*2)

multi of array  [24  6  8 10  6  4]


# create array


In [54]:
zeros = np.zeros((3,3))
print("Array of zeros \n", zeros)



ones = np.ones((3,3))
print("arrays of ones \n",ones)


constant_matrix =np.full((3,3),5)
print("arrays of constrant matrix \n",constant_matrix)


random_matrix = np.random.random((3,3))
print("arrays of random values matrix \n",random_matrix)

sequence_matrix = np.arange(0, 12 , 2).reshape(2, 3) # while reshaping any matrix you have to remember number of generating element == row*col
print("2x2 sequence matrix:\n", sequence_matrix)



Array of zeros 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
arrays of ones 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arrays of constrant matrix 
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
arrays of random values matrix 
 [[0.51088751 0.73388945 0.03010971]
 [0.13995257 0.24952475 0.77210455]
 [0.62527932 0.2610625  0.15671057]]
2x2 sequence matrix:
 [[ 0  2  4]
 [ 6  8 10]]


# Vector, Array and Tensor

## Vector
- **Definition:** A vector is a 1D quantity (like a list of numbers).
- **In NumPy:** Represented as a 1D array.
- **Shape:** `(n,)`
  
## Array (Matrix if 2D)

- **Definition:** General term in NumPy for 2-dimensional data.
- **Matrix:** Specifically a 2D array.
- **Shape:** (rows, columns)


## Tensor
- **Definition:** Generalization more than 2 dimensional arrays.
- **0D** → scalar (single number)
- **1D** → vector
- **2D** → matrix
- **3D or higher** → tensor

In [60]:
vector = np.array([1,2,3,4])
print("vector : \n", vector)

array = np.array([[1,2,3,4],
                  [1,2,3,4]])
print("Array : \n", array)

tensor = np.array([
    [[1,2,3,4],[1,2,3,4]],
    [[1,2,3,4],[1,2,3,4]]
    ])
print("Tensor : \n", tensor)



vector : 
 [1 2 3 4]
Array : 
 [[1 2 3 4]
 [1 2 3 4]]
Tensor : 
 [[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]


# Array Properties

In [62]:
arr = np.array([
    [1,2,3,4],
    [1,2,3,4]
])

print('shape ', arr.shape)
print('Dimension ',arr.ndim)
print('Size ',arr.size)
print("Data type ", arr.dtype)

shape  (2, 4)
Dimension  2
Size  8
Data type  int64


### Array Reshaping

In [74]:
arr = np.arange(12)
print("original array ",arr)

reshaped_array = arr.reshape((4,3))
print("reshaped array \n",reshaped_array)

print("flat array ", reshaped_array.flatten())
# ravel (return view, instead of copy)
print("raveled array ",reshaped_array.ravel())

# Transpose

print("Transpose ",reshaped_array.T)


original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
flat array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose  [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


# Numpy Array operations


In [78]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print("Basic slicing ",arr[2:7])
print("slicing with step ", arr[1:8:2])
print("negative indexing ",arr[-3])

Basic slicing  [2 3 4 5 6]
slicing with step  [1 3 5 7]
negative indexing  7


In [85]:
arr_2d  = np.array([[11,12,13,14],
                    [21,22,23,24],
                    [31,32,33,34]])
print(arr_2d)


print("values at 2nd row 3rd col ", arr_2d[1,2])
print("entire 1st row ",arr_2d[0])
print("entire 1st column ",arr_2d[:,0])


[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
values at 2nd row 3rd col  23
entire 1st row  [11 12 13 14]
entire 1st column  [11 21 31]


## Sorting

In [ ]:
unsorted_1Darray = np.array(
    [2,4,5,1,4]
)

unsorted_2Darray = np.array([
    [2,4,5,1],
    [4,7,2,7],
    [3,5,2,6,]
])



print("sorted array \n",np.sort(unsorted_1Darray))

print("sorted array(left to right) \n",np.sort(unsorted_2Darray,axis=1)) #if axis = 1 it will sort left to right and if axis =0 it will sort top to bottom

print("sorted array(top to bottom) \n",np.sort(unsorted_2Darray,axis=0)) #if axis = 1 it will sort left to right and if axis =0 it will sort top to bottom

print(unsorted_2Darray[1])


sorted array 
 [1 2 4 4 5]
sorted array(left to right) 
 [[1 2 4 5]
 [2 4 7 7]
 [2 3 5 6]]
sorted array(top to bottom) 
 [[2 4 2 1]
 [3 5 2 6]
 [4 7 5 7]]
