In [12]:
import numpy as np

In [13]:
arr_1d = np.array([12,3,4,5,3,2])
print("1D array", arr_1d)

1D array [12  3  4  5  3  2]


In [14]:
arr_2d = np.array([[1,2,3,4],[2,3,4,5]])
print("2d array:\n" ,arr_2d)

2d array:
 [[1 2 3 4]
 [2 3 4 5]]


In [15]:
print(arr_2d)

[[1 2 3 4]
 [2 3 4 5]]
